// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_def.proto

#ifndef PROTOBUF_msg_5fdef_2eproto__INCLUDED
#define PROTOBUF_msg_5fdef_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_msg_5fdef_2eproto();
void protobuf_AssignDesc_msg_5fdef_2eproto();
void protobuf_ShutdownFile_msg_5fdef_2eproto();

class ReqHead;
class RespHead;

// ===================================================================

class ReqHead : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ReqHead) */ {
 public:
  ReqHead();
  virtual ~ReqHead();

  ReqHead(const ReqHead& from);

  inline ReqHead& operator=(const ReqHead& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqHead& default_instance();

  void Swap(ReqHead* other);

  // implements Message ----------------------------------------------

  inline ReqHead* New() const { return New(NULL); }

  ReqHead* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReqHead& from);
  void MergeFrom(const ReqHead& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ReqHead* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 msg_id = 1;
  void clear_msg_id();
  static const int kMsgIdFieldNumber = 1;
  ::google::protobuf::uint32 msg_id() const;
  void set_msg_id(::google::protobuf::uint32 value);

  // optional uint32 msg_seq = 2;
  void clear_msg_seq();
  static const int kMsgSeqFieldNumber = 2;
  ::google::protobuf::uint32 msg_seq() const;
  void set_msg_seq(::google::protobuf::uint32 value);

  // optional uint32 src = 3;
  void clear_src();
  static const int kSrcFieldNumber = 3;
  ::google::protobuf::uint32 src() const;
  void set_src(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ReqHead)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 msg_id_;
  ::google::protobuf::uint32 msg_seq_;
  ::google::protobuf::uint32 src_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_msg_5fdef_2eproto();
  friend void protobuf_AssignDesc_msg_5fdef_2eproto();
  friend void protobuf_ShutdownFile_msg_5fdef_2eproto();

  void InitAsDefaultInstance();
  static ReqHead* default_instance_;
};
// -------------------------------------------------------------------

class RespHead : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RespHead) */ {
 public:
  RespHead();
  virtual ~RespHead();

  RespHead(const RespHead& from);

  inline RespHead& operator=(const RespHead& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RespHead& default_instance();

  void Swap(RespHead* other);

  // implements Message ----------------------------------------------

  inline RespHead* New() const { return New(NULL); }

  RespHead* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RespHead& from);
  void MergeFrom(const RespHead& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RespHead* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 msg_id = 1;
  void clear_msg_id();
  static const int kMsgIdFieldNumber = 1;
  ::google::protobuf::uint32 msg_id() const;
  void set_msg_id(::google::protobuf::uint32 value);

  // optional uint32 msg_seq = 2;
  void clear_msg_seq();
  static const int kMsgSeqFieldNumber = 2;
  ::google::protobuf::uint32 msg_seq() const;
  void set_msg_seq(::google::protobuf::uint32 value);

  // optional int32 result = 3;
  void clear_result();
  static const int kResultFieldNumber = 3;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RespHead)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 msg_id_;
  ::google::protobuf::uint32 msg_seq_;
  ::google::protobuf::int32 result_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_msg_5fdef_2eproto();
  friend void protobuf_AssignDesc_msg_5fdef_2eproto();
  friend void protobuf_ShutdownFile_msg_5fdef_2eproto();

  void InitAsDefaultInstance();
  static RespHead* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ReqHead

// optional uint32 msg_id = 1;
inline void ReqHead::clear_msg_id() {
  msg_id_ = 0u;
}
inline ::google::protobuf::uint32 ReqHead::msg_id() const {
  // @@protoc_insertion_point(field_get:ReqHead.msg_id)
  return msg_id_;
}
inline void ReqHead::set_msg_id(::google::protobuf::uint32 value) {
  
  msg_id_ = value;
  // @@protoc_insertion_point(field_set:ReqHead.msg_id)
}

// optional uint32 msg_seq = 2;
inline void ReqHead::clear_msg_seq() {
  msg_seq_ = 0u;
}
inline ::google::protobuf::uint32 ReqHead::msg_seq() const {
  // @@protoc_insertion_point(field_get:ReqHead.msg_seq)
  return msg_seq_;
}
inline void ReqHead::set_msg_seq(::google::protobuf::uint32 value) {
  
  msg_seq_ = value;
  // @@protoc_insertion_point(field_set:ReqHead.msg_seq)
}

// optional uint32 src = 3;
inline void ReqHead::clear_src() {
  src_ = 0u;
}
inline ::google::protobuf::uint32 ReqHead::src() const {
  // @@protoc_insertion_point(field_get:ReqHead.src)
  return src_;
}
inline void ReqHead::set_src(::google::protobuf::uint32 value) {
  
  src_ = value;
  // @@protoc_insertion_point(field_set:ReqHead.src)
}

// -------------------------------------------------------------------

// RespHead

// optional uint32 msg_id = 1;
inline void RespHead::clear_msg_id() {
  msg_id_ = 0u;
}
inline ::google::protobuf::uint32 RespHead::msg_id() const {
  // @@protoc_insertion_point(field_get:RespHead.msg_id)
  return msg_id_;
}
inline void RespHead::set_msg_id(::google::protobuf::uint32 value) {
  
  msg_id_ = value;
  // @@protoc_insertion_point(field_set:RespHead.msg_id)
}

// optional uint32 msg_seq = 2;
inline void RespHead::clear_msg_seq() {
  msg_seq_ = 0u;
}
inline ::google::protobuf::uint32 RespHead::msg_seq() const {
  // @@protoc_insertion_point(field_get:RespHead.msg_seq)
  return msg_seq_;
}
inline void RespHead::set_msg_seq(::google::protobuf::uint32 value) {
  
  msg_seq_ = value;
  // @@protoc_insertion_point(field_set:RespHead.msg_seq)
}

// optional int32 result = 3;
inline void RespHead::clear_result() {
  result_ = 0;
}
inline ::google::protobuf::int32 RespHead::result() const {
  // @@protoc_insertion_point(field_get:RespHead.result)
  return result_;
}
inline void RespHead::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:RespHead.result)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_5fdef_2eproto__INCLUDED
